package podgorskip.managementSystem.utils;

public enum Privileges {
    ADD_AGENT, REMOVE_AGENT, REMOVE_CLIENT, REMOVE_OWNER,
    CHECK_AGENTS, CHECK_ESTATES, REPORT_OFFER, POST_OFFER, DELETE_OFFER,
    CHECK_AGENT_CALLENDAR, CHECK_SCHEDULED_MEETINGS, SCHEDULE_MEETING
}
