package podgorskip.managementSystem.utils;

public enum Privileges {
    ADD_AGENT, ADD_BROKER, ADD_ACCOUNTANT, REMOVE_AGENT, REMOVE_BROKER, REMOVE_ACCOUNTANT,
    CHECK_AGENTS, CHECK_ESTATES, REPORT_OFFER, POST_OFFER, DELETE_OFFER
}
